### ISSUE TITLE
Promregator Lite Tracking Issue

### ISSUE THREAD

**Issue by checketts** [promregator/promregator#220]
The Promregator Lite effort is being broken into several smaller PRs. This issue is intended to track those PRs and features all together.

## Summary / Problem Statement
Promregator lite is a simplified approach that remove the feature where scraping Promregator's metric endpoint would serve up all individual target's metrics as well. In deprecating that feature, it focuses on a few other changes to make running Promregator simpler.

## Features

- [ ] Add Kotlin support
- [ ] Migrate shared code to Kotlin
- [ ] Create dummy endpoints
- [ ] #201 #158  Document new HTTP Service discovery
- [ ] Expand configuration based on CF annotations (auth, route, etc)

## Bonus features (These features aren't blocking, but are part of the bigger effort)
- [ ] #210 singleTargetMetrics hides scrape failure
- [ ] #209 Add support for multiple CF APIs
- [ ] Add support for listing apps that are stopped/etc

More bulletpoints will be added as PRs are created.

**Comment by eaglerainbow** [comment]
@checketts fyi, I am currently struggling with a proper Kotlin setup in my IDE. Apparently, there's a mismatch in the metadata version of the compiled binaries:
![grafik](https://user-images.githubusercontent.com/12811079/162810979-ea25f856-20b6-46da-9831-dbca045461d6.png)

Moreover, the environment seems not to be too happy about the fact that the kotlin artifacts are stored in `src/main/java`, but it more expects it in `src/main/kotlin`. From my perspective, moving the stuff there is the right thing as you also had put

https://github.com/promregator/promregator/blob/3796954ab51bd0f9297303ca308721534bdc9951/pom.xml#L430

in there.

**Comment by checketts** [comment]
This sounds like the IDE you are using is trying to configure its own Kotlin compiler/plugin (which also explains why it is expecting Kotlin files in one specific location)

What tooling are you using? I can try reproducing it locally.

**Comment by eaglerainbow** [comment]
Ah, that might be a good hint:

I am currently using a rather oldish Eclipse IDE for Java Developers Version 2019-12 (4.14.0). 
The eclipse kotlin plugin that I was using was severely outdated (something like version `0.8.9` from 2019 somewhere - perhaps the initial version). I now ran the update routine and I got a 1.5.31-something. That made the IDE change its mind ;)

**Comment by eaglerainbow** [comment]
Can we still move the stuff to `/src/main/kotlin`? Looks cleaner to me...

**Comment by checketts** [comment]
Sure! I was keeping it in `/src/main/java` to keep changes incremental. I'll do that in the currently open PR

**Comment by checketts** [comment]
In the v2 discovery I removed all cfClient caching and just create a new client each time. This is possible because I simplified the target resolved/instance scanner.

I think this is the best approach since the worst Promregator bugs have been around the cfClient's behavior.

**Comment by eaglerainbow** [comment]
What do you exactly mean with `cfClient` here? If we end up creating whole new connection pools and cf-java-client starting query for a new access JWT for each request, we will kill the UAA server on the server side.

**Comment by checketts** [comment]
Sorry for not being clearer. I didn't mean a new client for _every_ request to the CF API, but rather every _series_ of requests that fully populates the discovery.

Pseudo code:

1. /discovery endpoint is called
2. `resolveTargets()` is called
3. new CF Client is created (could be cached for X minutes here)
4. The client is then passed down the chain to all the other calls (and reused)

This way we could easily configure the client to be cached for a configurable duration or catch and error and use that as a signal to refresh it without potentially resetting a client that is being used by another thread.

**Comment by eaglerainbow** [comment]
> I didn't mean a new client for every request to the CF API, but rather every series of requests that fully populates the discovery.

Okay, understood. Did you already consider the following scenario?
* Promregator is deployed to CF as app
* There are 2+ instances running; note that these are separate containers
* A single `/discovery` request is sent. Let's say instance 0 takes it ==> the caches will be filled there. The caches for instances 1 and following will not be filled.
* The /discovery document contains hundreds of targets.
* Single Endpoint Scraping kicks in and hundreds of targets are equally distributed over the 20s interval ==> within the first second there will be dozens of requests to Promregator
* Also instances 1 and following will be hit by requests to the single scraping endpoint; we will have cache misses.

**Comment by checketts** [comment]
Yes. That is handled in the `[DiscoveryService](https://github.com/promregator/promregator/pull/223/files#diff-9690465aabb33078011c457d24d720491ae0d4b6b22fb7ce73831a6fd9f4386eR19)`, since it uses an async cache to gate the access.

The async cache holds a value for 60 seconds, and returns the previous value, unless the value is over 60 seconds old, then it returns the old value and refreshes the cache in the background.

This also avoids a 'cache stampede' since subsequent requests all wait on the same async call to finish for them to continue.

**Comment by eaglerainbow** [comment]
> Yes. That is handled in the [DiscoveryService](https://github.com/promregator/promregator/pull/223/files#diff-9690465aabb33078011c457d24d720491ae0d4b6b22fb7ce73831a6fd9f4386eR19), since it uses an async cache to gate the access.

Okay, but this still means that you don't have the complete context in the request parameters - you still will require to have your own ConnectionContext up and running. You may have so in the background, but then your Connection Context of the background process becomes shared again and hence will become long-living. I assume we then will have the same issue as in #222, as we are not working on "fresh ConnectionContexts" again. So, this approach might be better, but also isn't the silver bullet.
